import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { IdeasSidebarShadcn } from "@/components/personal-components/ideas-sidebar-shadcn";
import { AuthProvider } from "@/contexts/AuthContext";
import { Header } from "@/components/ui/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <IdeasSidebarShadcn>
            <div className="flex-1 min-w-0">
              <Header />
              {children}
            </div>
          </IdeasSidebarShadcn>
        </AuthProvider>
      </body>
    </html>
  );
}
